/**
 * Asset Manifest (Auto-generated)
 *
 * DO NOT EDIT - This file is generated by lib/brand-knowledge/generate.ts
 * Run: npm run generate:brand-index
 */

import { AssetEntry } from './types';

export const ASSET_MANIFEST: {
  logos: AssetEntry[];
  fonts: AssetEntry[];
  illustrations: AssetEntry[];
  images: AssetEntry[];
  textures: AssetEntry[];
  icons: AssetEntry[];
} = {
  "logos": [
    {
      "path": "/assets/logos/brandmark-charcoal.svg",
      "category": "logos",
      "filename": "brandmark-charcoal.svg",
      "variant": "brandmark-charcoal",
      "description": "brandmark logo in charcoal"
    },
    {
      "path": "/assets/logos/brandmark-glass.svg",
      "category": "logos",
      "filename": "brandmark-glass.svg",
      "variant": "brandmark-glass",
      "description": "brandmark logo in glass"
    },
    {
      "path": "/assets/logos/brandmark-vanilla.svg",
      "category": "logos",
      "filename": "brandmark-vanilla.svg",
      "variant": "brandmark-vanilla",
      "description": "brandmark logo in vanilla"
    },
    {
      "path": "/assets/logos/combo-icon-glass.svg",
      "category": "logos",
      "filename": "combo-icon-glass.svg",
      "variant": "combo-icon-glass",
      "description": "combo-icon logo in glass"
    },
    {
      "path": "/assets/logos/combo-icon-vanilla.svg",
      "category": "logos",
      "filename": "combo-icon-vanilla.svg",
      "variant": "combo-icon-vanilla",
      "description": "combo-icon logo in vanilla"
    },
    {
      "path": "/assets/logos/combo-text-glass.svg",
      "category": "logos",
      "filename": "combo-text-glass.svg",
      "variant": "combo-text-glass",
      "description": "combo-text logo in glass"
    },
    {
      "path": "/assets/logos/combo-text-vanilla.svg",
      "category": "logos",
      "filename": "combo-text-vanilla.svg",
      "variant": "combo-text-vanilla",
      "description": "combo-text logo in vanilla"
    },
    {
      "path": "/assets/logos/core-charcoal.svg",
      "category": "logos",
      "filename": "core-charcoal.svg",
      "variant": "core-charcoal",
      "description": "core logo in charcoal"
    },
    {
      "path": "/assets/logos/core-glass.svg",
      "category": "logos",
      "filename": "core-glass.svg",
      "variant": "core-glass",
      "description": "core logo in glass"
    },
    {
      "path": "/assets/logos/core.svg",
      "category": "logos",
      "filename": "core.svg",
      "variant": "core-default",
      "description": "core logo in default"
    },
    {
      "path": "/assets/logos/filled-charcoal.svg",
      "category": "logos",
      "filename": "filled-charcoal.svg",
      "variant": "filled-charcoal",
      "description": "filled logo in charcoal"
    },
    {
      "path": "/assets/logos/filled-glass.svg",
      "category": "logos",
      "filename": "filled-glass.svg",
      "variant": "filled-glass",
      "description": "filled logo in glass"
    },
    {
      "path": "/assets/logos/filled.svg",
      "category": "logos",
      "filename": "filled.svg",
      "variant": "filled-default",
      "description": "filled logo in default"
    },
    {
      "path": "/assets/logos/horizontal-charcoal.svg",
      "category": "logos",
      "filename": "horizontal-charcoal.svg",
      "variant": "horizontal-charcoal",
      "description": "horizontal logo in charcoal"
    },
    {
      "path": "/assets/logos/horizontal-glass.svg",
      "category": "logos",
      "filename": "horizontal-glass.svg",
      "variant": "horizontal-glass",
      "description": "horizontal logo in glass"
    },
    {
      "path": "/assets/logos/horizontal-vanilla.svg",
      "category": "logos",
      "filename": "horizontal-vanilla.svg",
      "variant": "horizontal-vanilla",
      "description": "horizontal logo in vanilla"
    },
    {
      "path": "/assets/logos/logo_main_combo_charcoal.svg",
      "category": "logos",
      "filename": "logo_main_combo_charcoal.svg",
      "variant": "combo-charcoal",
      "description": "combo logo in charcoal"
    },
    {
      "path": "/assets/logos/logo_main_combo_glass.svg",
      "category": "logos",
      "filename": "logo_main_combo_glass.svg",
      "variant": "combo-glass",
      "description": "combo logo in glass"
    },
    {
      "path": "/assets/logos/logo_main_combo_vanilla.svg",
      "category": "logos",
      "filename": "logo_main_combo_vanilla.svg",
      "variant": "combo-vanilla",
      "description": "combo logo in vanilla"
    },
    {
      "path": "/assets/logos/outline-charcoal.svg",
      "category": "logos",
      "filename": "outline-charcoal.svg",
      "variant": "outline-charcoal",
      "description": "outline logo in charcoal"
    },
    {
      "path": "/assets/logos/outline-glass.svg",
      "category": "logos",
      "filename": "outline-glass.svg",
      "variant": "outline-glass",
      "description": "outline logo in glass"
    },
    {
      "path": "/assets/logos/outline.svg",
      "category": "logos",
      "filename": "outline.svg",
      "variant": "outline-default",
      "description": "outline logo in default"
    },
    {
      "path": "/assets/logos/stacked-charcoal.svg",
      "category": "logos",
      "filename": "stacked-charcoal.svg",
      "variant": "stacked-charcoal",
      "description": "stacked logo in charcoal"
    },
    {
      "path": "/assets/logos/stacked-glass.svg",
      "category": "logos",
      "filename": "stacked-glass.svg",
      "variant": "stacked-glass",
      "description": "stacked logo in glass"
    },
    {
      "path": "/assets/logos/stacked-vanilla.svg",
      "category": "logos",
      "filename": "stacked-vanilla.svg",
      "variant": "stacked-vanilla",
      "description": "stacked logo in vanilla"
    }
  ],
  "fonts": [
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayBlack 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayBlack 2.ttf",
      "variant": "neue-haas-grotesk-display-black",
      "description": "neue-haas-grotesk-display black"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayBlack.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayBlack.ttf",
      "variant": "neue-haas-grotesk-display-black",
      "description": "neue-haas-grotesk-display black"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayBlackItalic 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayBlackItalic 2.ttf",
      "variant": "neue-haas-grotesk-display-black",
      "description": "neue-haas-grotesk-display black"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayBlackItalic.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayBlackItalic.ttf",
      "variant": "neue-haas-grotesk-display-black",
      "description": "neue-haas-grotesk-display black"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayBold 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayBold 2.ttf",
      "variant": "neue-haas-grotesk-display-bold",
      "description": "neue-haas-grotesk-display bold"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayBold.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayBold.ttf",
      "variant": "neue-haas-grotesk-display-bold",
      "description": "neue-haas-grotesk-display bold"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayBoldItalic 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayBoldItalic 2.ttf",
      "variant": "neue-haas-grotesk-display-bold",
      "description": "neue-haas-grotesk-display bold"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayBoldItalic.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayBoldItalic.ttf",
      "variant": "neue-haas-grotesk-display-bold",
      "description": "neue-haas-grotesk-display bold"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayLight 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayLight 2.ttf",
      "variant": "neue-haas-grotesk-display-light",
      "description": "neue-haas-grotesk-display light"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayLight.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayLight.ttf",
      "variant": "neue-haas-grotesk-display-light",
      "description": "neue-haas-grotesk-display light"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayLightItalic 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayLightItalic 2.ttf",
      "variant": "neue-haas-grotesk-display-light",
      "description": "neue-haas-grotesk-display light"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayLightItalic.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayLightItalic.ttf",
      "variant": "neue-haas-grotesk-display-light",
      "description": "neue-haas-grotesk-display light"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayMedium 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayMedium 2.ttf",
      "variant": "neue-haas-grotesk-display-medium",
      "description": "neue-haas-grotesk-display medium"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayMedium.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayMedium.ttf",
      "variant": "neue-haas-grotesk-display-medium",
      "description": "neue-haas-grotesk-display medium"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayMediumItalic 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayMediumItalic 2.ttf",
      "variant": "neue-haas-grotesk-display-medium",
      "description": "neue-haas-grotesk-display medium"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayMediumItalic.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayMediumItalic.ttf",
      "variant": "neue-haas-grotesk-display-medium",
      "description": "neue-haas-grotesk-display medium"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayRoman 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayRoman 2.ttf",
      "variant": "neue-haas-grotesk-display-regular",
      "description": "neue-haas-grotesk-display regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayRoman.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayRoman.ttf",
      "variant": "neue-haas-grotesk-display-regular",
      "description": "neue-haas-grotesk-display regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayRomanItalic 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayRomanItalic 2.ttf",
      "variant": "neue-haas-grotesk-display-regular",
      "description": "neue-haas-grotesk-display regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayRomanItalic.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayRomanItalic.ttf",
      "variant": "neue-haas-grotesk-display-regular",
      "description": "neue-haas-grotesk-display regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayThin 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayThin 2.ttf",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayThin.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayThin.ttf",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayThinItalic 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayThinItalic 2.ttf",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayThinItalic.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayThinItalic.ttf",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayXThin 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayXThin 2.ttf",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayXThin.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayXThin.ttf",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayXThinItalic 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayXThinItalic 2.ttf",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayXThinItalic.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayXThinItalic.ttf",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayXXThin 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayXXThin 2.ttf",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayXXThin.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayXXThin.ttf",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayXXThinItalic 2.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayXXThinItalic 2.ttf",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Desktop/Display/NeueHaasDisplayXXThinItalic.ttf",
      "category": "fonts",
      "filename": "NeueHaasDisplayXXThinItalic.ttf",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayBlack 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayBlack 2.woff2",
      "variant": "neue-haas-grotesk-display-black",
      "description": "neue-haas-grotesk-display black"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayBlack.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayBlack.woff2",
      "variant": "neue-haas-grotesk-display-black",
      "description": "neue-haas-grotesk-display black"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayBlackItalic 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayBlackItalic 2.woff2",
      "variant": "neue-haas-grotesk-display-black",
      "description": "neue-haas-grotesk-display black"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayBlackItalic.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayBlackItalic.woff2",
      "variant": "neue-haas-grotesk-display-black",
      "description": "neue-haas-grotesk-display black"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayBold 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayBold 2.woff2",
      "variant": "neue-haas-grotesk-display-bold",
      "description": "neue-haas-grotesk-display bold"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayBold.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayBold.woff2",
      "variant": "neue-haas-grotesk-display-bold",
      "description": "neue-haas-grotesk-display bold"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayBoldItalic 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayBoldItalic 2.woff2",
      "variant": "neue-haas-grotesk-display-bold",
      "description": "neue-haas-grotesk-display bold"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayBoldItalic.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayBoldItalic.woff2",
      "variant": "neue-haas-grotesk-display-bold",
      "description": "neue-haas-grotesk-display bold"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayLight 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayLight 2.woff2",
      "variant": "neue-haas-grotesk-display-light",
      "description": "neue-haas-grotesk-display light"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayLight.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayLight.woff2",
      "variant": "neue-haas-grotesk-display-light",
      "description": "neue-haas-grotesk-display light"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayLightItalic 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayLightItalic 2.woff2",
      "variant": "neue-haas-grotesk-display-light",
      "description": "neue-haas-grotesk-display light"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayLightItalic.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayLightItalic.woff2",
      "variant": "neue-haas-grotesk-display-light",
      "description": "neue-haas-grotesk-display light"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayMedium 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayMedium 2.woff2",
      "variant": "neue-haas-grotesk-display-medium",
      "description": "neue-haas-grotesk-display medium"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayMedium.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayMedium.woff2",
      "variant": "neue-haas-grotesk-display-medium",
      "description": "neue-haas-grotesk-display medium"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayMediumItalic 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayMediumItalic 2.woff2",
      "variant": "neue-haas-grotesk-display-medium",
      "description": "neue-haas-grotesk-display medium"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayMediumItalic.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayMediumItalic.woff2",
      "variant": "neue-haas-grotesk-display-medium",
      "description": "neue-haas-grotesk-display medium"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayRoman 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayRoman 2.woff2",
      "variant": "neue-haas-grotesk-display-regular",
      "description": "neue-haas-grotesk-display regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayRoman.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayRoman.woff2",
      "variant": "neue-haas-grotesk-display-regular",
      "description": "neue-haas-grotesk-display regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayRomanItalic 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayRomanItalic 2.woff2",
      "variant": "neue-haas-grotesk-display-regular",
      "description": "neue-haas-grotesk-display regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayRomanItalic.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayRomanItalic.woff2",
      "variant": "neue-haas-grotesk-display-regular",
      "description": "neue-haas-grotesk-display regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayThin 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayThin 2.woff2",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayThin.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayThin.woff2",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayThinItalic 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayThinItalic 2.woff2",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayThinItalic.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayThinItalic.woff2",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayXThin 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayXThin 2.woff2",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayXThin.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayXThin.woff2",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayXThinItalic 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayXThinItalic 2.woff2",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayXThinItalic.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayXThinItalic.woff2",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayXXThin 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayXXThin 2.woff2",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayXXThin.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayXXThin.woff2",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayXXThinItalic 2.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayXXThinItalic 2.woff2",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk display/Web/NeueHassGrotesk_Display/NeueHaasDisplayXXThinItalic.woff2",
      "category": "fonts",
      "filename": "NeueHaasDisplayXXThinItalic.woff2",
      "variant": "neue-haas-grotesk-display-thin",
      "description": "neue-haas-grotesk-display thin"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Desktop/Text/NHaasGroteskTXPro-55Rg 2.otf",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-55Rg 2.otf",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Desktop/Text/NHaasGroteskTXPro-55Rg.otf",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-55Rg.otf",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Desktop/Text/NHaasGroteskTXPro-56It 2.otf",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-56It 2.otf",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Desktop/Text/NHaasGroteskTXPro-56It.otf",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-56It.otf",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Desktop/Text/NHaasGroteskTXPro-65Md 2.otf",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-65Md 2.otf",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Desktop/Text/NHaasGroteskTXPro-65Md.otf",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-65Md.otf",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Desktop/Text/NHaasGroteskTXPro-66MdIt 2.otf",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-66MdIt 2.otf",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Desktop/Text/NHaasGroteskTXPro-66MdIt.otf",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-66MdIt.otf",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Desktop/Text/NHaasGroteskTXPro-75Bd 2.otf",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-75Bd 2.otf",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Desktop/Text/NHaasGroteskTXPro-75Bd.otf",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-75Bd.otf",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Desktop/Text/NHaasGroteskTXPro-76BdIt 2.otf",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-76BdIt 2.otf",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Desktop/Text/NHaasGroteskTXPro-76BdIt.otf",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-76BdIt.otf",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Web/NeueHassGrotesk_Text/NHaasGroteskTXPro-55Rg 2.woff2",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-55Rg 2.woff2",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Web/NeueHassGrotesk_Text/NHaasGroteskTXPro-55Rg.woff2",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-55Rg.woff2",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Web/NeueHassGrotesk_Text/NHaasGroteskTXPro-56It 2.woff2",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-56It 2.woff2",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Web/NeueHassGrotesk_Text/NHaasGroteskTXPro-56It.woff2",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-56It.woff2",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Web/NeueHassGrotesk_Text/NHaasGroteskTXPro-65Md 2.woff2",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-65Md 2.woff2",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Web/NeueHassGrotesk_Text/NHaasGroteskTXPro-65Md.woff2",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-65Md.woff2",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Web/NeueHassGrotesk_Text/NHaasGroteskTXPro-66MdIt 2.woff2",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-66MdIt 2.woff2",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Web/NeueHassGrotesk_Text/NHaasGroteskTXPro-66MdIt.woff2",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-66MdIt.woff2",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Web/NeueHassGrotesk_Text/NHaasGroteskTXPro-75Bd 2.woff2",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-75Bd 2.woff2",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Web/NeueHassGrotesk_Text/NHaasGroteskTXPro-75Bd.woff2",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-75Bd.woff2",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Web/NeueHassGrotesk_Text/NHaasGroteskTXPro-76BdIt 2.woff2",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-76BdIt 2.woff2",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/neue-haas-grotesk text/Web/NeueHassGrotesk_Text/NHaasGroteskTXPro-76BdIt.woff2",
      "category": "fonts",
      "filename": "NHaasGroteskTXPro-76BdIt.woff2",
      "variant": "unknown-regular",
      "description": "unknown regular"
    },
    {
      "path": "/assets/fonts/offbit/Desktop/OffBit-101 2.ttf",
      "category": "fonts",
      "filename": "OffBit-101 2.ttf",
      "variant": "offbit-regular",
      "description": "offbit regular"
    },
    {
      "path": "/assets/fonts/offbit/Desktop/OffBit-101.ttf",
      "category": "fonts",
      "filename": "OffBit-101.ttf",
      "variant": "offbit-regular",
      "description": "offbit regular"
    },
    {
      "path": "/assets/fonts/offbit/Desktop/OffBit-101Bold 2.ttf",
      "category": "fonts",
      "filename": "OffBit-101Bold 2.ttf",
      "variant": "offbit-bold",
      "description": "offbit bold"
    },
    {
      "path": "/assets/fonts/offbit/Desktop/OffBit-101Bold.ttf",
      "category": "fonts",
      "filename": "OffBit-101Bold.ttf",
      "variant": "offbit-bold",
      "description": "offbit bold"
    },
    {
      "path": "/assets/fonts/offbit/Desktop/OffBit-Bold 2.ttf",
      "category": "fonts",
      "filename": "OffBit-Bold 2.ttf",
      "variant": "offbit-bold",
      "description": "offbit bold"
    },
    {
      "path": "/assets/fonts/offbit/Desktop/OffBit-Bold.ttf",
      "category": "fonts",
      "filename": "OffBit-Bold.ttf",
      "variant": "offbit-bold",
      "description": "offbit bold"
    },
    {
      "path": "/assets/fonts/offbit/Desktop/OffBit-Dot 2.ttf",
      "category": "fonts",
      "filename": "OffBit-Dot 2.ttf",
      "variant": "offbit-regular",
      "description": "offbit regular"
    },
    {
      "path": "/assets/fonts/offbit/Desktop/OffBit-Dot.ttf",
      "category": "fonts",
      "filename": "OffBit-Dot.ttf",
      "variant": "offbit-regular",
      "description": "offbit regular"
    },
    {
      "path": "/assets/fonts/offbit/Desktop/OffBit-DotBold 2.ttf",
      "category": "fonts",
      "filename": "OffBit-DotBold 2.ttf",
      "variant": "offbit-bold",
      "description": "offbit bold"
    },
    {
      "path": "/assets/fonts/offbit/Desktop/OffBit-DotBold.ttf",
      "category": "fonts",
      "filename": "OffBit-DotBold.ttf",
      "variant": "offbit-bold",
      "description": "offbit bold"
    },
    {
      "path": "/assets/fonts/offbit/Desktop/OffBit-Regular 2.ttf",
      "category": "fonts",
      "filename": "OffBit-Regular 2.ttf",
      "variant": "offbit-regular",
      "description": "offbit regular"
    },
    {
      "path": "/assets/fonts/offbit/Desktop/OffBit-Regular.ttf",
      "category": "fonts",
      "filename": "OffBit-Regular.ttf",
      "variant": "offbit-regular",
      "description": "offbit regular"
    },
    {
      "path": "/assets/fonts/offbit/offbit_Web/OffBit-101 2.woff2",
      "category": "fonts",
      "filename": "OffBit-101 2.woff2",
      "variant": "offbit-regular",
      "description": "offbit regular"
    },
    {
      "path": "/assets/fonts/offbit/offbit_Web/OffBit-101.woff2",
      "category": "fonts",
      "filename": "OffBit-101.woff2",
      "variant": "offbit-regular",
      "description": "offbit regular"
    },
    {
      "path": "/assets/fonts/offbit/offbit_Web/OffBit-101Bold 2.woff2",
      "category": "fonts",
      "filename": "OffBit-101Bold 2.woff2",
      "variant": "offbit-bold",
      "description": "offbit bold"
    },
    {
      "path": "/assets/fonts/offbit/offbit_Web/OffBit-101Bold.woff2",
      "category": "fonts",
      "filename": "OffBit-101Bold.woff2",
      "variant": "offbit-bold",
      "description": "offbit bold"
    },
    {
      "path": "/assets/fonts/offbit/offbit_Web/OffBit-Bold 2.woff2",
      "category": "fonts",
      "filename": "OffBit-Bold 2.woff2",
      "variant": "offbit-bold",
      "description": "offbit bold"
    },
    {
      "path": "/assets/fonts/offbit/offbit_Web/OffBit-Bold.woff2",
      "category": "fonts",
      "filename": "OffBit-Bold.woff2",
      "variant": "offbit-bold",
      "description": "offbit bold"
    },
    {
      "path": "/assets/fonts/offbit/offbit_Web/OffBit-Dot 2.woff2",
      "category": "fonts",
      "filename": "OffBit-Dot 2.woff2",
      "variant": "offbit-regular",
      "description": "offbit regular"
    },
    {
      "path": "/assets/fonts/offbit/offbit_Web/OffBit-Dot.woff2",
      "category": "fonts",
      "filename": "OffBit-Dot.woff2",
      "variant": "offbit-regular",
      "description": "offbit regular"
    },
    {
      "path": "/assets/fonts/offbit/offbit_Web/OffBit-DotBold 2.woff2",
      "category": "fonts",
      "filename": "OffBit-DotBold 2.woff2",
      "variant": "offbit-bold",
      "description": "offbit bold"
    },
    {
      "path": "/assets/fonts/offbit/offbit_Web/OffBit-DotBold.woff2",
      "category": "fonts",
      "filename": "OffBit-DotBold.woff2",
      "variant": "offbit-bold",
      "description": "offbit bold"
    },
    {
      "path": "/assets/fonts/offbit/offbit_Web/OffBit-Regular 2.woff2",
      "category": "fonts",
      "filename": "OffBit-Regular 2.woff2",
      "variant": "offbit-regular",
      "description": "offbit regular"
    },
    {
      "path": "/assets/fonts/offbit/offbit_Web/OffBit-Regular.woff2",
      "category": "fonts",
      "filename": "OffBit-Regular.woff2",
      "variant": "offbit-regular",
      "description": "offbit regular"
    }
  ],
  "illustrations": [
    {
      "path": "/assets/illustrations/Name=Atari  TYPE = triangle.svg",
      "category": "illustrations",
      "filename": "Name=Atari  TYPE = triangle.svg",
      "variant": "triangle",
      "description": "Atari  TYPE = triangle"
    },
    {
      "path": "/assets/illustrations/Name=B1  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=B1  TYPE = circle.svg",
      "variant": "circle",
      "description": "B1  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Blob  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Blob  TYPE = circle.svg",
      "variant": "circle",
      "description": "Blob  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Campfire  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Campfire  TYPE = circle.svg",
      "variant": "circle",
      "description": "Campfire  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Capture  TYPE = square.svg",
      "category": "illustrations",
      "filename": "Name=Capture  TYPE = square.svg",
      "variant": "square",
      "description": "Capture  TYPE = square"
    },
    {
      "path": "/assets/illustrations/Name=Chart  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Chart  TYPE = circle.svg",
      "variant": "circle",
      "description": "Chart  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Chart  TYPE = triangle.svg",
      "category": "illustrations",
      "filename": "Name=Chart  TYPE = triangle.svg",
      "variant": "triangle",
      "description": "Chart  TYPE = triangle"
    },
    {
      "path": "/assets/illustrations/Name=Circle Hexagon  TYPE = square.svg",
      "category": "illustrations",
      "filename": "Name=Circle Hexagon  TYPE = square.svg",
      "variant": "square",
      "description": "Circle Hexagon  TYPE = square"
    },
    {
      "path": "/assets/illustrations/Name=Circles Centered  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Circles Centered  TYPE = circle.svg",
      "variant": "circle",
      "description": "Circles Centered  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Circles Squared  TYPE = square.svg",
      "category": "illustrations",
      "filename": "Name=Circles Squared  TYPE = square.svg",
      "variant": "square",
      "description": "Circles Squared  TYPE = square"
    },
    {
      "path": "/assets/illustrations/Name=Clock  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Clock  TYPE = circle.svg",
      "variant": "circle",
      "description": "Clock  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Dots  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Dots  TYPE = circle.svg",
      "variant": "circle",
      "description": "Dots  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Expand  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Expand  TYPE = circle.svg",
      "variant": "circle",
      "description": "Expand  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Explode  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Explode  TYPE = circle.svg",
      "variant": "circle",
      "description": "Explode  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Globe  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Globe  TYPE = circle.svg",
      "variant": "circle",
      "description": "Globe  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Grid  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Grid  TYPE = circle.svg",
      "variant": "circle",
      "description": "Grid  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Half Lines  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Half Lines  TYPE = circle.svg",
      "variant": "circle",
      "description": "Half Lines  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Hex Center  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Hex Center  TYPE = circle.svg",
      "variant": "circle",
      "description": "Hex Center  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Implode  TYPE = square.svg",
      "category": "illustrations",
      "filename": "Name=Implode  TYPE = square.svg",
      "variant": "square",
      "description": "Implode  TYPE = square"
    },
    {
      "path": "/assets/illustrations/Name=LG_Ven Diagram  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=LG_Ven Diagram  TYPE = circle.svg",
      "variant": "circle",
      "description": "LG_Ven Diagram  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Peace  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Peace  TYPE = circle.svg",
      "variant": "circle",
      "description": "Peace  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Phillips  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Phillips  TYPE = circle.svg",
      "variant": "circle",
      "description": "Phillips  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Pills  TYPE = triangle.svg",
      "category": "illustrations",
      "filename": "Name=Pills  TYPE = triangle.svg",
      "variant": "triangle",
      "description": "Pills  TYPE = triangle"
    },
    {
      "path": "/assets/illustrations/Name=Plus  TYPE = square.svg",
      "category": "illustrations",
      "filename": "Name=Plus  TYPE = square.svg",
      "variant": "square",
      "description": "Plus  TYPE = square"
    },
    {
      "path": "/assets/illustrations/Name=Quarter Lines  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Quarter Lines  TYPE = circle.svg",
      "variant": "circle",
      "description": "Quarter Lines  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Random  TYPE = triangle.svg",
      "category": "illustrations",
      "filename": "Name=Random  TYPE = triangle.svg",
      "variant": "triangle",
      "description": "Random  TYPE = triangle"
    },
    {
      "path": "/assets/illustrations/Name=Recycle  TYPE = triangle.svg",
      "category": "illustrations",
      "filename": "Name=Recycle  TYPE = triangle.svg",
      "variant": "triangle",
      "description": "Recycle  TYPE = triangle"
    },
    {
      "path": "/assets/illustrations/Name=SM_Ven Diagram  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=SM_Ven Diagram  TYPE = circle.svg",
      "variant": "circle",
      "description": "SM_Ven Diagram  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Split Half  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Split Half  TYPE = circle.svg",
      "variant": "circle",
      "description": "Split Half  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Sprinkles  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Sprinkles  TYPE = circle.svg",
      "variant": "circle",
      "description": "Sprinkles  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Star  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Star  TYPE = circle.svg",
      "variant": "circle",
      "description": "Star  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Target  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Target  TYPE = circle.svg",
      "variant": "circle",
      "description": "Target  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Tic Tac Toe  TYPE = square.svg",
      "category": "illustrations",
      "filename": "Name=Tic Tac Toe  TYPE = square.svg",
      "variant": "square",
      "description": "Tic Tac Toe  TYPE = square"
    },
    {
      "path": "/assets/illustrations/Name=Vortex  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Vortex  TYPE = circle.svg",
      "variant": "circle",
      "description": "Vortex  TYPE = circle"
    },
    {
      "path": "/assets/illustrations/Name=Yin Yang  TYPE = circle.svg",
      "category": "illustrations",
      "filename": "Name=Yin Yang  TYPE = circle.svg",
      "variant": "circle",
      "description": "Yin Yang  TYPE = circle"
    }
  ],
  "images": [
    {
      "path": "/assets/images/auto-audi-quattro-urban-portrait.png",
      "category": "images",
      "filename": "auto-audi-quattro-urban-portrait.png",
      "variant": "auto",
      "description": "audi quattro urban portrait"
    },
    {
      "path": "/assets/images/auto-bmw-convertible-garage-night.png",
      "category": "images",
      "filename": "auto-bmw-convertible-garage-night.png",
      "variant": "auto",
      "description": "bmw convertible garage night"
    },
    {
      "path": "/assets/images/auto-desert-porsche-sunset-drift.png",
      "category": "images",
      "filename": "auto-desert-porsche-sunset-drift.png",
      "variant": "auto",
      "description": "desert porsche sunset drift"
    },
    {
      "path": "/assets/images/auto-night-drive-motion-blur.png",
      "category": "images",
      "filename": "auto-night-drive-motion-blur.png",
      "variant": "auto",
      "description": "night drive motion blur"
    },
    {
      "path": "/assets/images/auto-rally-porsche-night-racing.png",
      "category": "images",
      "filename": "auto-rally-porsche-night-racing.png",
      "variant": "auto",
      "description": "rally porsche night racing"
    },
    {
      "path": "/assets/images/auto-truck-wildflowers-mountain-dusk.png",
      "category": "images",
      "filename": "auto-truck-wildflowers-mountain-dusk.png",
      "variant": "auto",
      "description": "truck wildflowers mountain dusk"
    },
    {
      "path": "/assets/images/auto-vintage-interior-dashboard-sunset.png",
      "category": "images",
      "filename": "auto-vintage-interior-dashboard-sunset.png",
      "variant": "auto",
      "description": "vintage interior dashboard sunset"
    },
    {
      "path": "/assets/images/auto-white-porsche-desert-headlights.png",
      "category": "images",
      "filename": "auto-white-porsche-desert-headlights.png",
      "variant": "auto",
      "description": "white porsche desert headlights"
    },
    {
      "path": "/assets/images/escape-astronaut-sparkle-floating.png",
      "category": "images",
      "filename": "escape-astronaut-sparkle-floating.png",
      "variant": "escape",
      "description": "astronaut sparkle floating"
    },
    {
      "path": "/assets/images/escape-cliffside-workspace-ocean-view.png",
      "category": "images",
      "filename": "escape-cliffside-workspace-ocean-view.png",
      "variant": "escape",
      "description": "cliffside workspace ocean view"
    },
    {
      "path": "/assets/images/escape-coastal-laptop-remote-work.png",
      "category": "images",
      "filename": "escape-coastal-laptop-remote-work.png",
      "variant": "escape",
      "description": "coastal laptop remote work"
    },
    {
      "path": "/assets/images/escape-desert-silhouette-wanderer.png",
      "category": "images",
      "filename": "escape-desert-silhouette-wanderer.png",
      "variant": "escape",
      "description": "desert silhouette wanderer"
    },
    {
      "path": "/assets/images/escape-floating-sun-documents.png",
      "category": "images",
      "filename": "escape-floating-sun-documents.png",
      "variant": "escape",
      "description": "floating sun documents"
    },
    {
      "path": "/assets/images/escape-geometric-stairs-silhouette.png",
      "category": "images",
      "filename": "escape-geometric-stairs-silhouette.png",
      "variant": "escape",
      "description": "geometric stairs silhouette"
    },
    {
      "path": "/assets/images/escape-meadow-workspace-clouds.png",
      "category": "images",
      "filename": "escape-meadow-workspace-clouds.png",
      "variant": "escape",
      "description": "meadow workspace clouds"
    },
    {
      "path": "/assets/images/escape-mountain-desk-wilderness.png",
      "category": "images",
      "filename": "escape-mountain-desk-wilderness.png",
      "variant": "escape",
      "description": "mountain desk wilderness"
    },
    {
      "path": "/assets/images/feel-abstract-figure-warm-tones.png",
      "category": "images",
      "filename": "feel-abstract-figure-warm-tones.png",
      "variant": "feel",
      "description": "abstract figure warm tones"
    },
    {
      "path": "/assets/images/feel-delicate-abstract-movement.png",
      "category": "images",
      "filename": "feel-delicate-abstract-movement.png",
      "variant": "feel",
      "description": "delicate abstract movement"
    },
    {
      "path": "/assets/images/feel-dynamic-spin-motion-dress.png",
      "category": "images",
      "filename": "feel-dynamic-spin-motion-dress.png",
      "variant": "feel",
      "description": "dynamic spin motion dress"
    },
    {
      "path": "/assets/images/feel-ethereal-portrait-softness.png",
      "category": "images",
      "filename": "feel-ethereal-portrait-softness.png",
      "variant": "feel",
      "description": "ethereal portrait softness"
    },
    {
      "path": "/assets/images/feel-flowing-fabric-grace.png",
      "category": "images",
      "filename": "feel-flowing-fabric-grace.png",
      "variant": "feel",
      "description": "flowing fabric grace"
    },
    {
      "path": "/assets/images/feel-motion-blur-bouquet-flowers.png",
      "category": "images",
      "filename": "feel-motion-blur-bouquet-flowers.png",
      "variant": "feel",
      "description": "motion blur bouquet flowers"
    },
    {
      "path": "/assets/images/feel-portrait-shadow-play.png",
      "category": "images",
      "filename": "feel-portrait-shadow-play.png",
      "variant": "feel",
      "description": "portrait shadow play"
    },
    {
      "path": "/assets/images/feel-water-droplets-diagonal-reflection.png",
      "category": "images",
      "filename": "feel-water-droplets-diagonal-reflection.png",
      "variant": "feel",
      "description": "water droplets diagonal reflection"
    },
    {
      "path": "/assets/images/lifestyle-casual-chic-sidewalk.png",
      "category": "images",
      "filename": "lifestyle-casual-chic-sidewalk.png",
      "variant": "lifestyle",
      "description": "casual chic sidewalk"
    },
    {
      "path": "/assets/images/lifestyle-confident-street-style.png",
      "category": "images",
      "filename": "lifestyle-confident-street-style.png",
      "variant": "lifestyle",
      "description": "confident street style"
    },
    {
      "path": "/assets/images/lifestyle-contemporary-fashion-portrait.png",
      "category": "images",
      "filename": "lifestyle-contemporary-fashion-portrait.png",
      "variant": "lifestyle",
      "description": "contemporary fashion portrait"
    },
    {
      "path": "/assets/images/lifestyle-editorial-look-urban.png",
      "category": "images",
      "filename": "lifestyle-editorial-look-urban.png",
      "variant": "lifestyle",
      "description": "editorial look urban"
    },
    {
      "path": "/assets/images/lifestyle-minimalist-white-tones.png",
      "category": "images",
      "filename": "lifestyle-minimalist-white-tones.png",
      "variant": "lifestyle",
      "description": "minimalist white tones"
    },
    {
      "path": "/assets/images/lifestyle-modern-aesthetic-pose.png",
      "category": "images",
      "filename": "lifestyle-modern-aesthetic-pose.png",
      "variant": "lifestyle",
      "description": "modern aesthetic pose"
    },
    {
      "path": "/assets/images/lifestyle-urban-angel-street-fashion.png",
      "category": "images",
      "filename": "lifestyle-urban-angel-street-fashion.png",
      "variant": "lifestyle",
      "description": "urban angel street fashion"
    },
    {
      "path": "/assets/images/lifestyle-yellow-puffer-portrait.png",
      "category": "images",
      "filename": "lifestyle-yellow-puffer-portrait.png",
      "variant": "lifestyle",
      "description": "yellow puffer portrait"
    },
    {
      "path": "/assets/images/move-abstract-dance-flow.png",
      "category": "images",
      "filename": "move-abstract-dance-flow.png",
      "variant": "move",
      "description": "abstract dance flow"
    },
    {
      "path": "/assets/images/move-athletic-motion-energy.png",
      "category": "images",
      "filename": "move-athletic-motion-energy.png",
      "variant": "move",
      "description": "athletic motion energy"
    },
    {
      "path": "/assets/images/move-dynamic-figure-action.png",
      "category": "images",
      "filename": "move-dynamic-figure-action.png",
      "variant": "move",
      "description": "dynamic figure action"
    },
    {
      "path": "/assets/images/move-flowing-movement-grace.png",
      "category": "images",
      "filename": "move-flowing-movement-grace.png",
      "variant": "move",
      "description": "flowing movement grace"
    },
    {
      "path": "/assets/images/move-gesture-blur-dance.png",
      "category": "images",
      "filename": "move-gesture-blur-dance.png",
      "variant": "move",
      "description": "gesture blur dance"
    },
    {
      "path": "/assets/images/move-kinetic-energy-motion.png",
      "category": "images",
      "filename": "move-kinetic-energy-motion.png",
      "variant": "move",
      "description": "kinetic energy motion"
    },
    {
      "path": "/assets/images/move-palm-trees-runners-motion.png",
      "category": "images",
      "filename": "move-palm-trees-runners-motion.png",
      "variant": "move",
      "description": "palm trees runners motion"
    },
    {
      "path": "/assets/images/move-speed-blur-running.png",
      "category": "images",
      "filename": "move-speed-blur-running.png",
      "variant": "move",
      "description": "speed blur running"
    },
    {
      "path": "/assets/images/work-business-presentation.png",
      "category": "images",
      "filename": "work-business-presentation.png",
      "variant": "work",
      "description": "business presentation"
    },
    {
      "path": "/assets/images/work-conference-networking-event.png",
      "category": "images",
      "filename": "work-conference-networking-event.png",
      "variant": "work",
      "description": "conference networking event"
    },
    {
      "path": "/assets/images/work-corporate-environment.png",
      "category": "images",
      "filename": "work-corporate-environment.png",
      "variant": "work",
      "description": "corporate environment"
    },
    {
      "path": "/assets/images/work-iterra-brand-green-hills.png",
      "category": "images",
      "filename": "work-iterra-brand-green-hills.png",
      "variant": "work",
      "description": "iterra brand green hills"
    },
    {
      "path": "/assets/images/work-office-workspace-modern.png",
      "category": "images",
      "filename": "work-office-workspace-modern.png",
      "variant": "work",
      "description": "office workspace modern"
    },
    {
      "path": "/assets/images/work-professional-collaboration.png",
      "category": "images",
      "filename": "work-professional-collaboration.png",
      "variant": "work",
      "description": "professional collaboration"
    },
    {
      "path": "/assets/images/work-professional-setting.png",
      "category": "images",
      "filename": "work-professional-setting.png",
      "variant": "work",
      "description": "professional setting"
    },
    {
      "path": "/assets/images/work-team-meeting-discussion.png",
      "category": "images",
      "filename": "work-team-meeting-discussion.png",
      "variant": "work",
      "description": "team meeting discussion"
    }
  ],
  "textures": [
    {
      "path": "/assets/textures/GFX-DATABASE-SONIC-LINE-01.jpg",
      "category": "textures",
      "filename": "GFX-DATABASE-SONIC-LINE-01.jpg",
      "variant": "unknown",
      "description": "unknown texture"
    },
    {
      "path": "/assets/textures/GFX-DATABASE-SONIC-LINE-010.jpg",
      "category": "textures",
      "filename": "GFX-DATABASE-SONIC-LINE-010.jpg",
      "variant": "unknown",
      "description": "unknown texture"
    },
    {
      "path": "/assets/textures/GFX-DATABASE-SONIC-LINE-011.jpg",
      "category": "textures",
      "filename": "GFX-DATABASE-SONIC-LINE-011.jpg",
      "variant": "unknown",
      "description": "unknown texture"
    },
    {
      "path": "/assets/textures/GFX-DATABASE-SONIC-LINE-012.jpg",
      "category": "textures",
      "filename": "GFX-DATABASE-SONIC-LINE-012.jpg",
      "variant": "unknown",
      "description": "unknown texture"
    },
    {
      "path": "/assets/textures/GFX-DATABASE-SONIC-LINE-013.jpg",
      "category": "textures",
      "filename": "GFX-DATABASE-SONIC-LINE-013.jpg",
      "variant": "unknown",
      "description": "unknown texture"
    },
    {
      "path": "/assets/textures/GFX-DATABASE-SONIC-LINE-02.jpg",
      "category": "textures",
      "filename": "GFX-DATABASE-SONIC-LINE-02.jpg",
      "variant": "unknown",
      "description": "unknown texture"
    },
    {
      "path": "/assets/textures/GFX-DATABASE-SONIC-LINE-03.jpg",
      "category": "textures",
      "filename": "GFX-DATABASE-SONIC-LINE-03.jpg",
      "variant": "unknown",
      "description": "unknown texture"
    },
    {
      "path": "/assets/textures/GFX-DATABASE-SONIC-LINE-04.jpg",
      "category": "textures",
      "filename": "GFX-DATABASE-SONIC-LINE-04.jpg",
      "variant": "unknown",
      "description": "unknown texture"
    },
    {
      "path": "/assets/textures/GFX-DATABASE-SONIC-LINE-05.jpg",
      "category": "textures",
      "filename": "GFX-DATABASE-SONIC-LINE-05.jpg",
      "variant": "unknown",
      "description": "unknown texture"
    },
    {
      "path": "/assets/textures/GFX-DATABASE-SONIC-LINE-06.jpg",
      "category": "textures",
      "filename": "GFX-DATABASE-SONIC-LINE-06.jpg",
      "variant": "unknown",
      "description": "unknown texture"
    },
    {
      "path": "/assets/textures/GFX-DATABASE-SONIC-LINE-07.jpg",
      "category": "textures",
      "filename": "GFX-DATABASE-SONIC-LINE-07.jpg",
      "variant": "unknown",
      "description": "unknown texture"
    },
    {
      "path": "/assets/textures/GFX-DATABASE-SONIC-LINE-08.jpg",
      "category": "textures",
      "filename": "GFX-DATABASE-SONIC-LINE-08.jpg",
      "variant": "unknown",
      "description": "unknown texture"
    },
    {
      "path": "/assets/textures/GFX-DATABASE-SONIC-LINE-09.jpg",
      "category": "textures",
      "filename": "GFX-DATABASE-SONIC-LINE-09.jpg",
      "variant": "unknown",
      "description": "unknown texture"
    },
    {
      "path": "/assets/textures/texture_ascii_01_white_compressed.jpg",
      "category": "textures",
      "filename": "texture_ascii_01_white_compressed.jpg",
      "variant": "ascii",
      "description": "ascii texture"
    },
    {
      "path": "/assets/textures/texture_ascii_02_white_compressed.jpg",
      "category": "textures",
      "filename": "texture_ascii_02_white_compressed.jpg",
      "variant": "ascii",
      "description": "ascii texture"
    },
    {
      "path": "/assets/textures/texture_ascii_03_black_compressed.jpg",
      "category": "textures",
      "filename": "texture_ascii_03_black_compressed.jpg",
      "variant": "ascii",
      "description": "ascii texture"
    },
    {
      "path": "/assets/textures/texture_ascii_04_black_compressed.jpg",
      "category": "textures",
      "filename": "texture_ascii_04_black_compressed.jpg",
      "variant": "ascii",
      "description": "ascii texture"
    },
    {
      "path": "/assets/textures/texture_halftone_01_compressed.jpg",
      "category": "textures",
      "filename": "texture_halftone_01_compressed.jpg",
      "variant": "halftone",
      "description": "halftone texture"
    },
    {
      "path": "/assets/textures/texture_halftone_02_compressed.jpg",
      "category": "textures",
      "filename": "texture_halftone_02_compressed.jpg",
      "variant": "halftone",
      "description": "halftone texture"
    },
    {
      "path": "/assets/textures/texture_halftone_03_compressed.jpg",
      "category": "textures",
      "filename": "texture_halftone_03_compressed.jpg",
      "variant": "halftone",
      "description": "halftone texture"
    },
    {
      "path": "/assets/textures/texture_halftone_04_compressed.jpg",
      "category": "textures",
      "filename": "texture_halftone_04_compressed.jpg",
      "variant": "halftone",
      "description": "halftone texture"
    },
    {
      "path": "/assets/textures/texture_recycled-card_01_compressed.jpg",
      "category": "textures",
      "filename": "texture_recycled-card_01_compressed.jpg",
      "variant": "recycled-card",
      "description": "recycled-card texture"
    },
    {
      "path": "/assets/textures/texture_recycled-card_02_compressed.jpg",
      "category": "textures",
      "filename": "texture_recycled-card_02_compressed.jpg",
      "variant": "recycled-card",
      "description": "recycled-card texture"
    },
    {
      "path": "/assets/textures/texture_recycled-card_03_compressed.jpg",
      "category": "textures",
      "filename": "texture_recycled-card_03_compressed.jpg",
      "variant": "recycled-card",
      "description": "recycled-card texture"
    },
    {
      "path": "/assets/textures/texture_recycled-card_04_compressed.jpg",
      "category": "textures",
      "filename": "texture_recycled-card_04_compressed.jpg",
      "variant": "recycled-card",
      "description": "recycled-card texture"
    }
  ],
  "icons": [
    {
      "path": "/assets/icons/Linkree_figma_thumbnails.svg",
      "category": "icons",
      "filename": "Linkree_figma_thumbnails.svg",
      "description": "Linkree_figma_thumbnails"
    },
    {
      "path": "/assets/icons/Linkree_instagram_thumbnails.svg",
      "category": "icons",
      "filename": "Linkree_instagram_thumbnails.svg",
      "description": "Linkree_instagram_thumbnails"
    },
    {
      "path": "/assets/icons/Linkree_linkedin_thumbnails.svg",
      "category": "icons",
      "filename": "Linkree_linkedin_thumbnails.svg",
      "description": "Linkree_linkedin_thumbnails"
    },
    {
      "path": "/assets/icons/Linkree_medium_thumbnails.svg",
      "category": "icons",
      "filename": "Linkree_medium_thumbnails.svg",
      "description": "Linkree_medium_thumbnails"
    },
    {
      "path": "/assets/icons/Linkree_newsletter_thumbnails.svg",
      "category": "icons",
      "filename": "Linkree_newsletter_thumbnails.svg",
      "description": "Linkree_newsletter_thumbnails"
    },
    {
      "path": "/assets/icons/Linkree_substack_thumbnails.svg",
      "category": "icons",
      "filename": "Linkree_substack_thumbnails.svg",
      "description": "Linkree_substack_thumbnails"
    },
    {
      "path": "/assets/icons/Linkree_website_thumbnails.svg",
      "category": "icons",
      "filename": "Linkree_website_thumbnails.svg",
      "description": "Linkree_website_thumbnails"
    },
    {
      "path": "/assets/icons/Linkree_youtube_thumbnails.svg",
      "category": "icons",
      "filename": "Linkree_youtube_thumbnails.svg",
      "description": "Linkree_youtube_thumbnails"
    },
    {
      "path": "/assets/icons/OS_brand_favicon.png",
      "category": "icons",
      "filename": "OS_brand_favicon.png",
      "description": "OS_brand_favicon"
    }
  ]
};

// Get assets by category
export function getAssetsByCategory(category: keyof typeof ASSET_MANIFEST): AssetEntry[] {
  return ASSET_MANIFEST[category];
}

// Get all logos
export function getLogos(): AssetEntry[] {
  return ASSET_MANIFEST.logos;
}

// Get logos by color
export function getLogosByColor(color: 'vanilla' | 'charcoal' | 'glass'): AssetEntry[] {
  return ASSET_MANIFEST.logos.filter(l => l.variant?.includes(color));
}

// Get fonts
export function getFonts(): AssetEntry[] {
  return ASSET_MANIFEST.fonts;
}

// Get images by theme
export function getImagesByTheme(theme: 'auto' | 'lifestyle' | 'move' | 'escape' | 'work' | 'feel'): AssetEntry[] {
  return ASSET_MANIFEST.images.filter(i => i.variant === theme);
}

// Get all asset paths as a flat list
export function getAllAssetPaths(): string[] {
  return [
    ...ASSET_MANIFEST.logos.map(a => a.path),
    ...ASSET_MANIFEST.fonts.map(a => a.path),
    ...ASSET_MANIFEST.illustrations.map(a => a.path),
    ...ASSET_MANIFEST.images.map(a => a.path),
    ...ASSET_MANIFEST.textures.map(a => a.path),
    ...ASSET_MANIFEST.icons.map(a => a.path),
  ];
}

// Asset counts for summary
export const ASSET_COUNTS = {
  logos: 25,
  fonts: 112,
  illustrations: 35,
  images: 48,
  textures: 25,
  icons: 9,
  total: 254,
};
