/**
 * Asset Manifest (Auto-generated)
 *
 * DO NOT EDIT - This file is generated by lib/brand-knowledge/generate.ts
 * Run: npm run generate:brand-index
 */

import { AssetEntry } from './types';

export const ASSET_MANIFEST: {
  logos: AssetEntry[];
  fonts: AssetEntry[];
  illustrations: AssetEntry[];
  images: AssetEntry[];
  textures: AssetEntry[];
  icons: AssetEntry[];
} = {
  "logos": [],
  "fonts": [],
  "illustrations": [],
  "images": [],
  "textures": [],
  "icons": []
};

// Get assets by category
export function getAssetsByCategory(category: keyof typeof ASSET_MANIFEST): AssetEntry[] {
  return ASSET_MANIFEST[category];
}

// Get all logos
export function getLogos(): AssetEntry[] {
  return ASSET_MANIFEST.logos;
}

// Get logos by color
export function getLogosByColor(color: 'vanilla' | 'charcoal' | 'glass'): AssetEntry[] {
  return ASSET_MANIFEST.logos.filter(l => l.variant?.includes(color));
}

// Get fonts
export function getFonts(): AssetEntry[] {
  return ASSET_MANIFEST.fonts;
}

// Get images by theme
export function getImagesByTheme(theme: 'auto' | 'lifestyle' | 'move' | 'escape' | 'work' | 'feel'): AssetEntry[] {
  return ASSET_MANIFEST.images.filter(i => i.variant === theme);
}

// Get all asset paths as a flat list
export function getAllAssetPaths(): string[] {
  return [
    ...ASSET_MANIFEST.logos.map(a => a.path),
    ...ASSET_MANIFEST.fonts.map(a => a.path),
    ...ASSET_MANIFEST.illustrations.map(a => a.path),
    ...ASSET_MANIFEST.images.map(a => a.path),
    ...ASSET_MANIFEST.textures.map(a => a.path),
    ...ASSET_MANIFEST.icons.map(a => a.path),
  ];
}

// Asset counts for summary
export const ASSET_COUNTS = {
  logos: 0,
  fonts: 0,
  illustrations: 0,
  images: 0,
  textures: 0,
  icons: 0,
  total: 0,
};
