/**
 * Brand Documentation (Auto-generated)
 *
 * DO NOT EDIT - This file is generated by lib/brand-knowledge/generate.ts
 * Run: npm run generate:brand-index
 */

import { BrandDocument } from './types';

export const BRAND_DOCUMENTS: BrandDocument[] = [];

// Quick access by ID
export const BRAND_DOCS_BY_ID: Record<string, BrandDocument> = {

};

// Get document by ID
export function getBrandDocument(id: string): BrandDocument | undefined {
  return BRAND_DOCS_BY_ID[id];
}

// Get all documents
export function getAllBrandDocuments(): BrandDocument[] {
  return BRAND_DOCUMENTS;
}

// Search documents by keyword
export function searchDocuments(keyword: string): BrandDocument[] {
  const lower = keyword.toLowerCase();
  return BRAND_DOCUMENTS.filter(
    doc => doc.keywords.some(k => k.includes(lower)) ||
           doc.title.toLowerCase().includes(lower) ||
           doc.content.toLowerCase().includes(lower)
  );
}
